### ISSUE TITLE
vue-typeorm-app with live reload on Android Studio

### ISSUE THREAD

**Issue by Akaori** [jepiqueau/vue-typeorm-app#3]
Hi @jepiqueau ,

First of all, thank you to provide this very nice example.

I was using previous versions, and after update to your version example, I noticed I can't develop on android studio using live reload. Are you facing this same issue ?

**Comment by jepiqueau** [comment]
@Akaori I never test it with ` live reload` so I will have a look. From which previous versions have you been updated?

**Comment by jepiqueau** [comment]
@Akaori this is fixed in release 0.0.3

**Comment by Akaori** [comment]
Hi @jepiqueau. 
I updated from capacitor 2.9.10.

Thank you for fixing it. (I don't know if this bug has to do with something specif from my linux. But using `ionic cap run android -l` on your 0.0.3 release on windows worked fine).
