### ISSUE TITLE
How to generate migration files

### ISSUE THREAD

**Issue by Akaori** [jepiqueau/vue-typeorm-app#4]
Hello @jepiqueau ,

I don't have much experience with TypeORM and Capacitor-Sqlite, but I really like this match. I was wondering how could you handle to generate the migration files on this example.

I made a test removing all migration files, creating my own entities files, and running `typeorm migration:generate -n CreateDatabase`, but I get the following error:

```
TypeORMError: No connection options were found in any orm configuration files.
```

How did you generate your migration files? Am I doing something wrong?

**Comment by jepiqueau** [comment]
@Akaori hi, I am not a specialist of typeorm. I did know that we can generate it automatically from the entity. So I generate them manually.

**Comment by jepiqueau** [comment]
@Akaori according to the doc https://github.com/typeorm/typeorm/docs/migrations.md you need to create a configuratio

**Comment by Akaori** [comment]
Hi @jepiqueau, thanks for answering me.

Using automatic generation didn't work for me, but getting all sql expressions from logs was enough to create it manually like you did. 

Thank you for clarify how you did it.
