### ISSUE TITLE
[Question] How to persist with `localForage` ?

### ISSUE THREAD

**Issue by meddario** [jepiqueau/vue-typeorm-app#6]
Hi,

I'm trying to switch from using a `sqljs` TypeORM connection for development (and `capacitor` for production) to use `capacitor` on both environments, using `jeep-sqlite`.

My setup looks like the one in this repo (i post only the relevant function, where the connection is initialized, it's called before `app.mount("#app");` in main.ts):

```typescript
export async function createDatabaseConnection(platform: string) {
  const baseConnectionOptions = {
      logging: ["error", "query", "schema"],
      migrations: [
      // ...
      ],
      migrationsRun: true,
      entities: [
      // ...
      ],
    };

  const sqliteConnection = new SQLiteConnection(CapacitorSQLite);

  console.log("createDatabaseConnection", platform);
  // see https://github.com/capacitor-community/sqlite/blob/master/docs/Web-Usage.md
  if (platform == "web") {
    // Create the 'jeep-sqlite' Stencil component
    const jeepSqlite = document.createElement("jeep-sqlite");
    document.body.appendChild(jeepSqlite);
    await customElements.whenDefined("jeep-sqlite");
    // Initialize the Web store
    await sqliteConnection.initWebStore();
  }

  // when using Capacitor, you might want to close existing connections,
  // otherwise new connections will fail when using dev-live-reload
  // see https://github.com/capacitor-community/sqlite/issues/106
  CapacitorSQLite.checkConnectionsConsistency({
    dbNames: [], // i.e. "i expect no connections to be open"
  }).catch((e) => {
    // the plugin throws an error when closing connections. we can ignore
    // that since it is expected behaviour
    console.error(e);
    return {};
  });


  const connectionOptions = {
    type: "capacitor",
    database: "my-database",
    driver: sqliteConnection,
  } as ConnectionOptions;

  return await createConnection(
    Object.assign(baseConnectionOptions, connectionOptions) as ConnectionOptions
  );
};
```

as opposed to (old code with `sqljs`):

```typescript
export async function createDatabaseConnection(isHybridPlatform) {
  const baseConnectionOptions = {
      logging: ["error", "query", "schema"],
      migrations: [
      // ...
      ],
      migrationsRun: true,
      entities: [
      // ...
      ],
    };

  if (isHybridPlatform) {
    const sqliteConnection = new SQLiteConnection(CapacitorSQLite);
    // Running on device or emulator
    connectionOptions = {
      type: "capacitor", // or "cordova" for `cordova-sqlite-storage`
      database: "my-database",
      driver: sqliteConnection, // remove "driver" and add `location: "default"` for `cordova-sqlite-storage`
    };
  } else {
    // Running app in browser
    connectionOptions = {
      type: "sqljs",
      autoSave: true,
      location: "browser",
      useLocalForage: true,
    };
  }
  return await createConnection(
    Object.assign(baseConnectionOptions, connectionOptions) as ConnectionOptions
  );
};
```

The problem I have is that in the `sqljs` way (with `autosave`), the database was always saved, with `capacitor` and `jeep-sqlite` the database is lost when I reload the page (or when the live reload refreshes the app). Is there a way to persist the database to indexed db? In the `jeep-sqlite` description `localForage` is mentioned <https://github.com/jepiqueau/jeep-sqlite#jeep-sqlite>, but I don't understand how to activate it. Can you give some pointers?

Thanks in advance,
Dario

**Comment by meddario** [comment]
For the record, for now I was able to save to IndexedDB in this way (`setInterval` + `beforeunload`, see the "Save in-memory SQLite to IndexedDB" part inside the `if (platform == "web")`):

```typescript
export async function createDatabaseConnection(platform: string) {
  // ... as before

  if (platform == "web") {
    // ... as before

    // Save in-memory SQLite to IndexedDB
    const saveStore = async () => {
      await jeepSqlite.saveToStore({ database: DATABASE_NAME });
    };
    // Interval to sync to storage
    const interval = window.setInterval(saveStore, 10000);
    const beforeUnloadListener = async () => {
      window.clearInterval(interval);

      // Save again on unload
      saveStore();

      return;
    };
    window.addEventListener("beforeunload", beforeUnloadListener, { capture: true });
  }
  // ... as before
};
```

BTW, I checked how this was done in the `sqljs` case, it overrides `release()` and `commitTransaction()` from TypeORM https://github.com/typeorm/typeorm/blob/master/src/driver/sqljs/SqljsQueryRunner.ts#L45 . I don't think that this would be feasible with Capacitor, since the `capacitor` driver in TypeORM doesn't directly use `jeep-sqlite`.

If someone has a better idea I would be happy to know! Thanks!

**Comment by jepiqueau** [comment]
@meddario Look at the doc there is a `saveToStore` method  only for the web which allows to save the in-memory database to store you can use at any time in your code. otherwise the `db.close()` or the `closeConnection()`will do it also. it is better to use saveToStore after some large transaction. It is only valid for web not for native so you have to test if the platform is web. Hope this will help you

**Comment by meddario** [comment]
@jepiqueau ok, thanks, so, basically, the solution I added in the comment above should be correct: I added a `setInterval` that calls `saveToStore()` every 10 seconds, and, to ensure that data is saved, I also call `saveToStore()` inside the `beforeunload` (***) handler, so it's written if the tab is closed or refreshed.

(***) I'm not sure that the `beforeunload` will work if the data is too large, but this is just for development, in order to avoid losing all the data at every page reload, I won't use this in production (production uses proper SQLite from Android/iOs).

**Comment by jepiqueau** [comment]
@meddario sorry i did not look in detail what you had suggested but it is correct. I was busy on another plugin and want to answer you. When going to native  do not forget to remove jeep-sqlite and the wasm file from the assets to decrease the size of your build.

**Comment by jepiqueau** [comment]
@meddario feel free to close the issue

**Comment by meddario** [comment]
> @meddario sorry i did not look in detail what you had suggested but it is correct. I was busy on another plugin and want to answer you. When going to native do not forget to remove jeep-sqlite and the wasm file from the assets to decrease the size of your build.

Nevermind, thank you for the answer!
